### ISSUE TITLE
CSUnits on NuGet

### ISSUE THREAD

**Issue by anders9ustafsson** [CaffeinatedCoder/Caffeinated.Toolbox#1]
Dear Ricardo,

I have been trying to contact you via NuGet without success, so I'll give this route a try as well. I am the author of _csunits_, which you have published on NuGet. 

Since I have recently made a major overhaul of the library, I would now like to be able to publish updated packages on NuGet, and I would like to use the original name.

Therefore I would like to ask you to add me as a co-owner of _csunits_ on NuGet so that I can easily upload new packages.

Thanks in advance!

Anders Gustafsson
Cureos AB

**Comment by CaffeinatedCoder** [comment]
Sure, please just send me your username you are using on NuGet, then I will add you as an owner to the package. 
If you prefer to send it via mail: ricardo (at) mr-gross.de
